// Generated by CoffeeScript 1.4.0
/*
# Console-lacking browsers.
*/

if (!(window.console && console.log)) {
  (function() {
    var console, method, methods, noop, _i, _len;
    noop = function() {};
    methods = ['assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error', 'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log', 'markTimeline', 'profile', 'profileEnd', 'markTimeline', 'table', 'time', 'timeEnd', 'timeStamp', 'trace', 'warn'];
    console = window.console = {};
    for (_i = 0, _len = methods.length; _i < _len; _i++) {
      method = methods[_i];
      console[method] = noop;
    }
  })();
}

$(function() {
  var $contact, $content, $counter, $mail, $message, charCount, correctMail, decode, mailCheck, meny, spam_txt, token_txt;
  $content = $('#content');
  /* 
  	# Contact form manager.
  */

  $contact = $('#contact-js');
  $mail = $('#mail');
  $message = $('#message');
  $counter = $('.char-counter');
  mailCheck = /@/;
  charCount = function() {
    var count;
    count = $message.val().length;
    $counter.html(count);
    return $counter.css({
      'color': "hsl(210, " + (count / 3) + "%, 50%",
      'text-shadow': "0 0 1 px hsl(210, " + (count / 3) + "%, 70%)"
    });
  };
  $message.on('keyup', charCount);
  $message.change(charCount);
  $contact.on('submit', function() {
    var address, input;
    address = $mail.val();
    input = $message.val();
    return address !== '' && input !== '' && mailCheck.test(address);
  });
  /* 
  	# Scrolling with anchor links.
  */

  $('ul.nav a, a.to-top').on('click', function(e) {
    var destination;
    e.preventDefault();
    destination = $($(this).attr('href')).offset().top;
    return $content.stop().animate({
      scrollTop: destination
    }, 500);
  });
  /* 
  	# Information hiding for spam bots.
  */

  decode = function(arr) {
    return arr.reduce((function(acc, car, i) {
      if (acc == null) {
        acc = '';
      }
      return acc + String.fromCharCode(car - i);
    }), '');
  };
  spam_txt = [116, 105, 107, 101, 68, 121, 110, 112, 106, 55, 119, 112];
  correctMail = decode(spam_txt);
  $('a.remplacement').attr('href', "mailto:" + correctMail);
  $('span.remplacement').html(correctMail);
  token_txt = [54, 103, 54, 101, 60, 58, 54, 64, 106, 57, 110, 66, 69, 114, 64, 70, 118, 117, 68, 117, 75, 122, 71, 75, 123, 76, 74, 126, 128, 86, 79, 82];
  $contact.attr('action', "http://getsimpleform.com/messages?form_api_token=" + decode(token_txt));
  /*
  	# Initializing
  */

  meny = Meny.create();
  $('h1').fitText(0.7);
  $('abbr').tooltip();
  return $('#thibaudcolas').tooltip();
});
