// Generated by CoffeeScript 1.4.0
/*
# FitText.js 1.1 in CoffeeScript
#
# Copyright 2011, Dave Rupert http://daverupert.com
# Released under the WTFPL license
# http://sam.zoy.org/wtfpl/
#
# Date: Thu May 05 14:23:00 2011 -0600
*/

var $;

$ = jQuery;

$.fn.fitText = function(compressor, options) {
  var settings;
  if (compressor == null) {
    compressor = 1;
  }
  settings = {
    'minFontSize': Number.NEGATIVE_INFINITY,
    'maxFontSize': Number.POSITIVE_INFINITY
  };
  if (options) {
    $.extend(settings, options);
  }
  return this.each(function() {
    var $this, resizer;
    $this = $(this);
    resizer = function() {
      var newSize;
      newSize = $this.width() / (compressor * 10);
      return $this.css('font-size', Math.max(Math.min(newSize, parseFloat(settings.maxFontSize)), parseFloat(settings.minFontSize)));
    };
    resizer();
    return $(window).resize(resizer);
  });
};
