// Generated by CoffeeScript 1.4.0
/*
 * CoffeeScript Pretty Date — Inspired by John Resig's JavaScript PrettyDate
 * Copyright (c) 2011 John Resig (ejohn.org)
 * Licensed under the MIT and GPL licenses.
*/

var prettyDate;

prettyDate = function(time) {
  var date, dayDiff, secDiff;
  date = new Date(time != null ? (time.replace(/-/g, '/')).replace(/[TZ]/g, ' ') : '');
  secDiff = (new Date().getTime() - date.getTime()) / 1000;
  dayDiff = Math.floor(secDiff / 86400);
  if (isNaN(dayDiff || dayDiff < 0 || dayDiff >= 31)) {
    return;
  }
  return dayDiff === 0 && (secDiff < 60 && ("" + secDiff + "s") || secDiff < 3600 && ("" + (Math.floor(secDiff / 60)) + "m") || secDiff < 86400 && ("" + (Math.floor(secDiff / 3600)) + "h")) || dayDiff === 1 && "Hier" || dayDiff < 7 && ("" + dayDiff + "j") || dayDiff < 31 && ("" + (Math.ceil(dayDiff / 7)) + "w");
};
