name: CI
on:
  push:
    branches-ignore: 
      - "gh-pages"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
      - id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: bundle install
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      - run: npm run dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ls
      - run: ls dist
      - uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: dist
          clean: true
